# Pytorch Gradients

## Import

!pip install torch

In [20]:
# pip install torch

In [21]:
import torch

In [22]:
x = torch.tensor(2.0,requires_grad=True)

In [23]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [24]:
print(y)
# Türevin alınmış Y içine 2 koyulmuş

tensor(63., grad_fn=<AddBackward0>)


In [25]:
y.backward()

In [26]:
type(y)

torch.Tensor

In [27]:
x.grad
# Y yerine 2 koyulmuş, EĞİM verir

tensor(93.)

In [28]:
print(x.grad)

tensor(93.)


In [29]:
x = torch.tensor([[1.,2.,3],[3,2,1]], requires_grad=True)
print(x)
# sayından sonra nokta olmadan hata veriyor float olmadıgı için.

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [30]:
y = 3*x + 2
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [31]:
z = 2*y**2
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [32]:
out = z.mean()

In [33]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [34]:
out.backward()
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
