In [1]:
import numpy as np

In [2]:
list = [1,2,3]
list

In [8]:
type(list)

list

In [5]:
arr = np.array(list)

In [6]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [10]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [17]:
np.random.rand(2,3)

array([[0.76179873, 0.56555308, 0.82293455],
       [0.06824531, 0.02305873, 0.40957517]])

In [18]:
np.random.rand(4)

array([0.42569614, 0.76805559, 0.41877395, 0.41214092])

In [21]:
np.random.randint(10,20,(4,4))

array([[16, 13, 16, 11],
       [18, 17, 10, 18],
       [11, 12, 17, 16],
       [17, 11, 13, 14]])

In [24]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [26]:
arr= np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
narr = arr.reshape(3,5)

In [33]:
narr.max()

14

In [34]:
narr.min()

0

In [35]:
narr.argmin()

0

In [43]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[2:6]

array([2, 3, 4, 5])

In [45]:
arr += 2
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [53]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])