# Tensor Operations
This section covers:
* Indexing and slicing
* Reshaping tensors (tensor views)
* Tensor arithmetic and basic operations
* Dot products
* Matrix multiplication
* Additional, more advanced operations

## Perform standard imports

In [24]:
import torch
import numpy as np

In [25]:
x= torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [26]:
x[1,0]

tensor(2)

In [27]:
type(x[1,0])

torch.Tensor

In [28]:
# Grabbing the right hand column as a (3,1) slice
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [29]:
# Grabbing the right hand column values
x[:,1]

tensor([1, 3, 5])

In [30]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
x.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [33]:
x
# x is unchanged

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
z = x.view(2,5)
x[0]=234
print(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


In [35]:
x.view(2,-1)
# By passing in -1 PyTorch will 
# ...infer the correct value from the given tensor

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [36]:
x.view(5,-1)

tensor([[234,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [37]:
x.view(-1,5)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [38]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [39]:
print(torch.add(a, b))

tensor([5., 7., 9.])


In [40]:
a.mul(b)

tensor([ 4., 10., 18.])

In [41]:
a.div(b)

tensor([0.2500, 0.4000, 0.5000])

In [42]:
a.add_(b)  # equivalent to a=torch.add(a,b)
print(a)
#İşlemden sonra _ varsa kalıcı olur

tensor([5., 7., 9.])


In [43]:
a

tensor([5., 7., 9.])

In [44]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [45]:
a.mul(b)

tensor([ 4., 10., 18.])

In [47]:
a.dot(b)

tensor(32.)

In [48]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])


In [49]:
print('a x b: ',torch.mm(a,b).size())

a x b:  torch.Size([2, 2])


In [50]:
print(torch.mm(a,b))

tensor([[56., 62.],
        [80., 89.]])


In [51]:
print(a.mm(b))

tensor([[56., 62.],
        [80., 89.]])


In [52]:
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])


In [53]:
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


In [54]:
x = torch.tensor([2.,5.,8.,14.])
x.norm()

tensor(17.)

In [55]:
x = torch.ones(3,7)
x.numel()

21

This can be useful in certain calculations like Mean Squared Error:<br>
<tt>
def mse(t1, t2):<br>
&nbsp;&nbsp;&nbsp;&nbsp;diff = t1 - t2<br>
    &nbsp;&nbsp;&nbsp;&nbsp;return torch.sum(diff * diff) / diff<strong>.numel()</strong></tt>

In [56]:
np.random.seed(42)
torch.manual_seed(42);  # the semicolon suppresses the jupyter output line

In [57]:
arr = np.random.randint(0,5,6)
print(arr)

[3 4 2 4 4 1]


In [59]:
x = torch.from_numpy(arr)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [60]:
x = x.type(torch.int64)
# x = x.type(torch.LongTensor)
print(x.type())

torch.LongTensor


In [61]:
x = x.view(3,2)
# x = x.reshape(3,2)
# x.resize_(3,2)
print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [62]:
print(x[:,1:])
# print(x[:,1])

tensor([[4],
        [4],
        [1]])


In [63]:
print(x*x)
# print(x**2)
# print(x.mul(x))
# print(x.pow(2))
# print(torch.mul(x,x))

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [64]:
y = torch.randint(0,5,(2,3))
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


In [65]:
print(x.mm(y)) 

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
