# TENSOR BASICS

!pip install torch

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.11.0+cpu'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [8]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [9]:
x = torch.as_tensor(arr)
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [10]:
x.dtype

torch.int32

In [11]:
arr2d = np.arange(0,12)
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr2d = arr2d.reshape(4,3)

In [13]:
x2 = torch.as_tensor(arr2d)
x2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)

In [14]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [15]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [16]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_tensor = torch.tensor(my_arr)

In [18]:
my_other_tensor = torch.from_numpy(my_arr)

In [19]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [20]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [21]:
my_arr[0] = 999
my_arr

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [22]:
my_tensor
# değişmedi

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [23]:
my_other_tensor
# from_numpy olunca değişti

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [29]:
a = torch.Tensor(data)  
# Equivalent to cc = torch.FloatTensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [30]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3], dtype=torch.int32) torch.IntTensor


In [31]:
c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3]) torch.LongTensor


In [34]:
x = torch.empty(4, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [35]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [36]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [38]:
x = torch.linspace(0,18,12).reshape(3,4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


In [39]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


In [40]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


In [41]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


In [42]:
x = torch.rand(4, 3)
print(x)

tensor([[0.8401, 0.1015, 0.5483],
        [0.9248, 0.9684, 0.6536],
        [0.4079, 0.0183, 0.9425],
        [0.4603, 0.7353, 0.0528]])


In [43]:
x = torch.randn(4, 3)
print(x)

tensor([[ 1.4050,  1.0803,  0.9644],
        [ 0.1097, -2.0425, -1.1260],
        [ 1.5346, -0.2695, -0.7975],
        [ 0.3450, -1.8583,  0.0097]])


In [44]:
torch.randint(low=0, high=10, size=(5,5))

tensor([[9, 3, 1, 6, 9],
        [1, 5, 9, 2, 5],
        [2, 3, 0, 2, 4],
        [2, 3, 9, 4, 4],
        [6, 0, 7, 5, 8]])

In [45]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [46]:
x2 = torch.randn_like(x)
print(x2)

tensor([[ 1.1983, -0.5369,  0.3601, -0.5366,  0.2413],
        [-2.1999, -0.3622,  0.7251, -1.0592, -2.9755]])


In [47]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [48]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [49]:
x.shape

torch.Size([2, 3])

In [50]:
x.size()  # equivalent to x.shape

torch.Size([2, 3])

In [51]:
x.device

device(type='cpu')

In [52]:
x.layout

torch.strided