# **Introduction to TensorFlow**

## Tensor

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.10.0


In [4]:
scalar = tf.constant(7)

In [5]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
scalar.ndim

0

In [8]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [9]:
vector.ndim

1

In [10]:
matrix = tf.constant([[10,8],
                      [7,10]])

In [11]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 7, 10]])>

In [12]:
matrix.ndim

2

In [13]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [15]:
another_matrix.ndim

2

In [16]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [17]:
tensor.ndim

3

## tf.Variable()

In [19]:
changeable = tf.Variable([10,7])
unchangable = tf.constant([10,7])
changeable, unchangable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [21]:
changeable[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [23]:
unchangable[0].assign(4)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating Tensors

In [24]:
rand_1 = tf.random.Generator.from_seed(42)
rand_1 = rand_1.normal(shape=(3,2))

rand_2 = tf.random.Generator.from_seed(42)
rand_2 = rand_2.normal(shape=(3,2))

rand_1, rand_2, rand_2==rand_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [26]:
rand_3 = tf.random.Generator.from_seed(42)
rand_3 = rand_3.normal(shape=(3, 2))

rand_4 = tf.random.Generator.from_seed(11)
rand_4 = rand_4.normal(shape=(3, 2))

rand_3, rand_4, rand_1 == rand_3, rand_3 == rand_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [27]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

2

In [28]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [31]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [39]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [40]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [41]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [44]:
import numpy as np
array = np.arange(1,25)

a = tf.constant(array, shape=(2,4,3))
array, a

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

* **Shape:** The length (number of elements) of each of the dimensions of a tensor.
* **Rank:** The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* **Axis** or **Dimension:** A particular dimension of a tensor.
* **Size:** The total number of items in the tensor.

In [47]:
rank4 = tf.zeros([2,2,3,4])
rank4

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [49]:
print("Datatype of every element:", rank4.dtype)
print("Number of dimensions (rank):", rank4.ndim)
print("Shape of tensor:", rank4.shape)
print("Elements along axis 0 of tensor:", rank4.shape[0])
print("Elements along last axis of tensor:", rank4.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank4).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 2, 3, 4)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 4
Total number of elements (2*3*4*5): 48


In [51]:
rank4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [52]:
rank4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [53]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [54]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] 
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

## Tensor Operasyonları

In [55]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [56]:
tensor+5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 12],
       [ 8,  9]])>

In [57]:
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [58]:
tf.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]])>

In [60]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [62]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [64]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [65]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [67]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [68]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [69]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [70]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [71]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [74]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [75]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [76]:
tf.matmul(X, tf.reshape(Y, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [78]:
Y.shape

TensorShape([3, 2])

In [79]:
tf.reshape(Y, (2,3)).shape

TensorShape([2, 3])

In [80]:
tf.transpose(Y).shape

TensorShape([2, 3])

In [81]:
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


## Datatype of Tensor

In [82]:
B = tf.constant([1.7, 7.4])
C = tf.constant([1, 7])
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [83]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [84]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [85]:
D = tf.constant([-7,10])

In [86]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

## Min Max Mean Sum 

In [87]:
E = tf.constant(np.random.randint(0,100,50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([69, 78, 29, 82, 38, 35, 25, 69, 12,  1, 62, 69, 69, 28,  4,  4, 42,
       57, 71, 15, 36,  2, 38,  3, 80,  1, 55, 58, 58, 44, 57, 25, 26, 91,
       66, 10, 49, 53, 83,  6, 55, 86, 63,  9, 66, 36, 54,  3, 95, 64])>

In [88]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [89]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [90]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=44>

In [91]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2231>

In [92]:
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [93]:
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [95]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.7061811 , 0.24365866, 0.53504426, 0.79115118, 0.2189713 ,
       0.80298546, 0.2787173 , 0.21522498, 0.68520966, 0.43993947,
       0.1295397 , 0.36728304, 0.24762661, 0.52597338, 0.49154641,
       0.77944834, 0.29362374, 0.66375224, 0.06044916, 0.81173384,
       0.89031974, 0.63596393, 0.68437301, 0.12842065, 0.11121761,
       0.86698933, 0.95409623, 0.10864539, 0.66335791, 0.59300898,
       0.2753518 , 0.65174493, 0.22580274, 0.55483897, 0.96355904,
       0.80995541, 0.61831628, 0.23269647, 0.14041188, 0.36247016,
       0.61025344, 0.36633615, 0.07203227, 0.87351175, 0.1950937 ,
       0.46755839, 0.6563647 , 0.4005772 , 0.98126908, 0.57769558])>

In [96]:
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 48
The maximum value of F is: 0.9812690786437264
Using tf.argmax() to index F, the maximum value of F is: 0.9812690786437264
Are the two max values the same (they should be)? True


## Squeezing Tensor

In [97]:
G = tf.constant(np.random.randint(0,100,50), shape = (1,1,1,1,50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [98]:
G_sq = tf.squeeze(G)
G_sq.shape, G_sq.ndim

(TensorShape([50]), 1)

## One-hot Encoding

In [99]:
some_list = [0, 1, 2, 3] 

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [100]:
tf.one_hot(some_list, depth=4, on_value="We are alive", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'We are alive', b'Offline', b'Offline', b'Offline'],
       [b'Offline', b'We are alive', b'Offline', b'Offline'],
       [b'Offline', b'Offline', b'We are alive', b'Offline'],
       [b'Offline', b'Offline', b'Offline', b'We are alive']],
      dtype=object)>

## Square, Log

In [101]:
H = tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [102]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [103]:
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [106]:
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [107]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [108]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [110]:
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [111]:
I.assign([0,1,2,3,49])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 49])>

In [112]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 49])>

In [113]:
I.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 59])>

In [114]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 59])>

## Tensors & NumPy

In [115]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [116]:
J.numpy()

array([ 3.,  7., 10.])

In [117]:
type(J.numpy())

numpy.ndarray

In [119]:
numpy_J = tf.constant(np.array([3., 7., 10.])) # numpy default float 64
tensor_J = tf.constant([3., 7., 10.]) # tensor default float 16
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## @tf.function

In [122]:
def func(x,y):
    return x**2 + y

x = tf.constant(np.arange(0,10))
y = tf.constant(np.arange(10,20))
func(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [124]:
@tf.function
def tf_func(x,y):
    return x**2 + y

tf_func(x,y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## Access to GPU

In [125]:
print(tf.config.list_physical_devices("GPU"))

[]


In [128]:
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [127]:
!nvidia-smi

Tue Sep 13 19:56:29 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.79       Driver Version: 511.79       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   49C    P5     7W /  N/A |   1167MiB /  4096MiB |     31%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------